server.port: 8083
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        email: #Channel Name
          binder: kafka
          destination: emailQueue #topic name
        order:
          binder: kafka
          destination: orderQueue