server.port: 8083
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          headers: email, order
          brokers:
            - localhost:9092
      bindings:
        email:
          binder: kafka
          destination: emailQueue
          group: emailQueue-group
          content-type: application/json
        order:
          binder: kafka
          destination: orderQueue
          group: orderQueue-group
          content-type: application/json


