server:
  port: 8082
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          headers: email, order
          brokers:
            - localhost:9092
      bindings:
        order:
          binder: kafka
          destination: orderQueue
          content-type: text/plain
          group: orderQueue-group